### ISSUE TITLE
Not catched exception while generating new hash

### ISSUE THREAD

**Issue by Kajoj** [MCMi460/NSO-RPC#1]
After working for 10 to 20 minutes application throws an exception as follows
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Username\Documents\NSO-RPC-main\client\cli.py", line 51, in background
    self.update()
  File "C:\Users\Username\Documents\NSO-RPC-main\client\cli.py", line 35, in update
    self.api.updateLogin()
  File "C:\Users\Username\Documents\NSO-RPC-main\client\api\__init__.py", line 48, in updateLogin
    self.login = Login(self.userInfo, self.accessToken, self.guid)
  File "C:\Users\Username\Documents\NSO-RPC-main\client\api\__init__.py", line 147, in __init__
    self.flapg = Flapg(self.accessToken, self.timestamp, self.guid).get()
  File "C:\Users\Username\Documents\NSO-RPC-main\client\api\__init__.py", line 112, in __init__
    'x-hash': s2s(id_token, timestamp).getHash(),
  File "C:\Users\Username\Documents\NSO-RPC-main\client\api\__init__.py", line 104, in getHash
    return json.loads(response.text)['hash']
KeyError: 'hash'
```

Problem is with s2s api and that app exhaust request limit. I don't know what is the limit, but fast fix that worked for me is as follows:
```
    def background(self):
        second = 60
        while True:
            if self.running:
                if second == 60:
                    try:
                        self.update()
                        second = 0
                    except KeyError:
                        second = 0
                second += 1
            else:
                second = 55
            time.sleep(1)
```
To prepare better solution application should generate hash less frequently to not exhaust hash generation limit.

**Comment by MCMi460** [comment]
If this is still an issue in the future, comment here and I'll increase the refresh time for hash generation again.
