### ISSUE TITLE
Invalid Token on MacOS

### ISSUE THREAD

**Issue by Polyglot-Coder** [MCMi460/NSO-RPC#105]
I'm assuming Nintendo did something to mess with F-Tokens? 

As of today, I am getting `Login returns {'status': 9403, 'errorMessage': 'Invalid token.', 'correlationId': '4d917775-b2609d97'}`

If there is anything I can test on my end, I'll be glad to figure out the issue on my system but I feel that it might not be an issue with NSO-RPC itself.

Just incase my computer is an M1 Mac Ultra Studio with with Ventura 13.4

**Comment by HotaruBlaze** [comment]
> I'm assuming Nintendo did something to mess with F-Tokens?

Yep, F-Token stuff is broken

```

Traceback (most recent call last):
  File "app.py", line 711, in <module>
  File "app.py", line 281, in selfService
  File "app.py", line 401, in changeState
  File "app.py", line 398, in changeState
  File "cli.py", line 89, in update
  File "api\__init__.py", line 147, in updateLogin
Exception: Failure with authorization: 'result'
Login returns {'status': 9403, 'errorMessage': 'Invalid token.', 'correlationId': '767e5079-2ceeab04'}
```

**Comment by HotaruBlaze** [comment]
Looking like F-Token stuff is fixed again 👍

**Comment by Maronbeere** [comment]
Same error appears again as of today, with different parameters:
```
Traceback (most recent call last):
  File "cli.py", line 85, in update
  File "api\__init__.py", line 162, in getSelf
  File "api\__init__.py", line 175, in getFriends
  File "api\__init__.py", line 340, in populateList
  File "api\__init__.py", line 337, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\__init__.py", line 151, in updateLogin
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 764, in <module>
  File "app.py", line 303, in selfService
  File "app.py", line 422, in changeState
  File "app.py", line 419, in changeState
  File "cli.py", line 91, in update
  File "api\__init__.py", line 153, in updateLogin
Exception: Failure with authorization: 'result'
Login returns {'status': 9403, 'errorMessage': 'Invalid token.', 'correlationId': 'f8f1211b-11d5e427'}

**Comment by HotaruBlaze** [comment]
@MCMi460 This issue should be closed now, although tis the same issue again this is old.
@Maronbeere See a new issue located here #127 with instructions.
