### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Peri0dic** [MCMi460/NSO-RPC#11]
It's been working perfectly for me for about a week but now on the most recent release when I try running the script after doing the login process I get this error:

> Traceback (most recent call last):
  File "cli.py", line 47, in update
  File "api\__init__.py", line 104, in getSelf
KeyError: 'result'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "app.py", line 481, in <module>
  File "app.py", line 147, in selfService
  File "app.py", line 245, in changeState
  File "cli.py", line 53, in update
  File "api\__init__.py", line 90, in updateLogin
  File "api\__init__.py", line 210, in __init__
  File "api\__init__.py", line 175, in __init__
  File "api\__init__.py", line 167, in getHash
KeyError: 'hash'

I have tried deleting the folder in documents and even manually putting in a session token.

EDIT: Should also note I am running windows.

**Comment by Peri0dic** [comment]
Ok now I can launch the app but my status is not updating, maybe my IP is blocked or something idk lol

**Comment by MCMi460** [comment]
> Ok now I can launch the app but my status is not updating, maybe my IP is blocked or something idk lol

This is referenced in issue #13 now. Thank you for bringing this to my attention.
