### ISSUE TITLE
Failed to execute script 'app' due to unhandled exception: Failure with authorization: 'result'.

### ISSUE THREAD

**Issue by BojayB** [MCMi460/NSO-RPC#123]
I only just downloaded this program, but I logged in with my main account. Everything seemed fine until I tried logging in with the account I should've in the first place, now it won't open and I get this error message each time I try to launch the program.

![image](https://github.com/MCMi460/NSO-RPC/assets/41974762/e1299526-5edf-4943-b461-f42a784d3dfa)

```
Traceback (most recent call last):
  File "cli.py", line 88, in update
  File "api\__init__.py", line 176, in getSelf
  File "api\__init__.py", line 189, in getFriends
  File "api\__init__.py", line 354, in populateList
  File "api\__init__.py", line 351, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\__init__.py", line 165, in updateLogin
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 833, in <module>
  File "app.py", line 352, in selfService
  File "app.py", line 487, in changeState
  File "app.py", line 484, in changeState
  File "cli.py", line 94, in update
  File "api\__init__.py", line 167, in updateLogin
Exception: Failure with authorization: 'result'
Login returns {'status': 9407, 'errorMessage': 'NSA not linked.', 'correlationId': '71559547-3b151f68'}
```

**Comment by BojayB** [comment]
I found the program folder and deleted it, now I'm reopening the program and after hitting "login" the application just closes with nothing else..

**Comment by MCMi460** [comment]
The error "NSA not linked" means that your Nintendo Account is not associated with a Nintendo Switch. Try making a profile with your account on your Switch.

**Comment by BojayB** [comment]
I have profiles with both my main account and the one I was trying to link to the NSORPC on my Switch..

**Comment by BojayB** [comment]
Yes, I was trying to link the wrong account because they both looked like the same email on the switch but were, in fact, two different emails. It's working completely fine now!!
