### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by rurikrok** [MCMi460/NSO-RPC#127]
Traceback (most recent call last):
  File "cli.py", line 88, in update
  File "api\__init__.py", line 176, in getSelf
  File "api\__init__.py", line 189, in getFriends
  File "api\__init__.py", line 354, in populateList
  File "api\__init__.py", line 351, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\__init__.py", line 165, in updateLogin
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 840, in <module>
  File "app.py", line 354, in selfService
  File "app.py", line 489, in changeState
  File "app.py", line 486, in changeState
  File "cli.py", line 94, in update
  File "api\__init__.py", line 167, in updateLogin
Exception: Failure with authorization: 'result'
Login returns {'status': 9403, 'errorMessage': 'Invalid token.', 'correlationId': 'ee385f01-6e447934'}

Deleting private.txt and updating token doesn't help

**Comment by rurikrok** [comment]
Thank you!

**Comment by Lukas-Batema** [comment]
[HotaruBlaze/NSO-RPC@`%23115PR-development` (release)](https://github.com/HotaruBlaze/NSO-RPC/releases/tag/%23115PR-development)

This is causing an infinite login loop and silent crash of the application on Windows 10.

**Comment by HotaruBlaze** [comment]
I'm aware theirs an issue where people need to de-delete their token files and login again, as it seems to be broken.

Silent crashing shouldn't be a thing unique to my build, unless the silent crashing is happening when trying to make the new token

**Comment by Lukas-Batema** [comment]
> I'm aware theirs an issue where people need to de-delete their token files and login again, as it seems to be broken.
> 
> Silent crashing shouldn't be a thing unique to my build, unless the silent crashing is happening when trying to make the new token

It's not even creating the tokens after logging in again, that's the issue

**Comment by HotaruBlaze** [comment]
So its most likely a race condition, maybe see if u can see a pattern in logs.txt

**Comment by Lukas-Batema** [comment]
> So its most likely a race condition, maybe see if u can see a pattern in logs.txt

Yeah, it worked after a seemingly random attempt count using the "select this account" link every time.

**Comment by HotaruBlaze** [comment]
I've got a new build generating that will override the version directly and does not depend on the overrideVersion logic and shouldn't suffer from the above issues and updated the above post with the new details

Please try it a couple of times and tell me if u still get those kinds of loops.

**Comment by Lukas-Batema** [comment]
> I've got a new build generating that will override the version directly and does not depend on the overrideVersion logic and shouldn't suffer from the above issues and updated the above post with the new details
> 
> 
> 
> Please try it a couple of times and tell me if u still get those kinds of loops.
> 
> 
> 
> _**Edit: Remember to delete the token files during testing**_

Will do!

**Comment by Lukas-Batema** [comment]
> I've got a new build generating that will override the version directly and does not depend on the overrideVersion logic and shouldn't suffer from the above issues and updated the above post with the new details
> 
> Please try it a couple of times and tell me if u still get those kinds of loops.
> 
> _**Edit: Remember to delete the token files during testing**_

Tested a couple times, deleteing the `tempToken.txt` and `private.txt` both times, and both worked off the bat.

**Comment by HotaruBlaze** [comment]
Both builds didn't exhibit issues for me, but it was always suspected the logic could be faulty. Just assumed it would only misfire once as that's the only time I saw a token error

**Comment by Lukas-Batema** [comment]
> Both builds didn't exhibit issues for me, but it was always suspected the logic could be faulty. Just assumed it would only misfire once as that's the only time I saw a token error.
> 
> I'll just assume the new build is good, no real reason for it not to be until 2.8.1 tokens aren't valid anymore

Has the 2.8.1 keys become invalidated? It is throwing this error again.

**Comment by HotaruBlaze** [comment]
the API that NSO-RPC uses for f tokens got updated earlier today to support 2.9.0. I just tested the official build and it works again!
