### ISSUE TITLE
application closes when i try to log in

### ISSUE THREAD

**Issue by kyuukyun** [MCMi460/NSO-RPC#128]
Hi, I'm using Windows 11. 
I downloaded the latest version and was able to open the application, but then when I try to log in the app closes. When I try to open it again, it displays this. (see below). I've tried deleting the private txt document and adding , "overrideVersion": "2.7.1". in the setting txt document (as its something I've been seeing while looking through the issues here) but it too causes the application to close when I log in. Am I doing something wrong? I'm not very knowledgeable when it comes to coding... so sorry!

Traceback (most recent call last):
  File "cli.py", line 85, in update
  File "api\__init__.py", line 162, in getSelf
  File "api\__init__.py", line 175, in getFriends
  File "api\__init__.py", line 340, in populateList
  File "api\__init__.py", line 337, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\__init__.py", line 151, in updateLogin
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 764, in <module>
  File "app.py", line 303, in selfService
  File "app.py", line 422, in changeState
  File "app.py", line 419, in changeState
  File "cli.py", line 91, in update
  File "api\__init__.py", line 153, in updateLogin
Exception: Failure with authorization: 'result'
Login returns {'status': 9403, 'errorMessage': 'Invalid token.', 'correlationId': 'ae4f0e60-53e9e019'}

**Comment by HotaruBlaze** [comment]
A couple of things to note here

1. This is the same issue as #127
2. Make sure you used the build with that issue and not the latest here, as its currently out of date.
3. Your saying u set 2.7.1, however the issue states to set it to 2.8.1

Note: My build sometimes crashes when initially making the token, its a flaw with it however wont give u the above error

**Comment by HotaruBlaze** [comment]
Make sure that settings.txt is configured as above, before private.txt & tempToken.txt exist else it'll still generate a bad token.

**Comment by yoSauxy** [comment]
Bless that worked! thank you so much
