### ISSUE TITLE
(MacOS) "Launch error"

### ISSUE THREAD

**Issue by Anhedonia7437** [MCMi460/NSO-RPC#129]
![image](https://github.com/MCMi460/NSO-RPC/assets/160989271/ef248300-6f35-4cea-b586-33806171ca83)

After downloading and installing the application on MacOS Sonoma 14.2.1 on my M1 Macbook Pro using mac-installer.dmg, I get this message on launch. 

"Launch error
Launch error
See the py2app website for debugging launch issues"

Responses are "Visit Website" and "Terminate". Visit website leads here https://py2app.readthedocs.io/en/latest/debugging.html
I got no results after following this guide. Terminate simply closes the application.

**Comment by HotaruBlaze** [comment]
Probably the same as #127, just macos wont give the same error prompt.

The steps should work the same on macos

**Comment by Anhedonia7437** [comment]
Unfortunately that didn't work. After deleting it from both the Applications and Documents folder, reinstalling it from the same installer (mac-installer.dmg) on the pre-release build, launching it, replacing the text in the settings.txt, and then attempting to log in, the program crashes. Trying to launch it again gives me the same message as earlier.

 I would guess that you're right that it's the same problem that's causing it, being the update that Nintendo pushed. But it might not have the same solution

**Comment by HotaruBlaze** [comment]
To get a more usable error, I'd recommend trying to run NSO-RPC directly in a terminal and seeing what the "Real" Error is
You should be able to with the following command: `./Applications/NSO-RPC.app/Contents/MacOS/NSO-RPC`

**Comment by Anhedonia7437** [comment]
`Last login: Thu Feb 22 23:07:51 on ttys000
jeremiah@jeremiahs-mbp ~ % /Applications/NSO-RPC.app/Contents/MacOS/NSO-RPC
Version override Detected: Replacing target version 2.9.0 with 2.8.1
Successfully Connected to Discord.
Traceback (most recent call last):
  File "cli.pyc", line 88, in update
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 181, in getSelf
    self.getFriends()
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 194, in getFriends
    list.populateList(self)
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 359, in populateList
    raise e
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 356, in populateList
    arr = json.loads(response.text)['result']['friends']
          ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 170, in updateLogin
    self.headers['Authorization'] = 'Bearer %s' % login.account['result'].get('webApiServerCredential').get('accessToken')  # Add authorization token
                                                  ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/NSO-RPC.app/Contents/Resources/__boot__.py", line 170, in <module>
    _run()
  File "/Applications/NSO-RPC.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/NSO-RPC.app/Contents/Resources/app.py", line 841, in <module>
    window.selfService()
  File "/Applications/NSO-RPC.app/Contents/Resources/app.py", line 354, in selfService
    self.changeState()
  File "/Applications/NSO-RPC.app/Contents/Resources/app.py", line 489, in changeState
    raise e
  File "/Applications/NSO-RPC.app/Contents/Resources/app.py", line 486, in changeState
    client.update()
  File "cli.pyc", line 94, in update
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 172, in updateLogin
    raise Exception('Failure with authorization: %s\nLogin returns %s' % (e, login.account))
Exception: Failure with authorization: 'result'
Login returns {'status': 9403, 'errorMessage': 'Invalid token.', 'correlationId': '263cf8c3-ab724123'}
2024-02-22 23:08:58.899 NSO-RPC[4685:567740] Launch error
2024-02-22 23:08:58.899 NSO-RPC[4685:567740] Launch error
See the py2app website for debugging launch issues`
Yeah, it looks to be the same problem. I'm just not exactly sure why #127's solution doesn't seem to work considering they're the same.

**Comment by HotaruBlaze** [comment]
make sure the settings.txt file exists before doing the copy link step, so only delete the two files mentioned in the issue if they exist

**Comment by Anhedonia7437** [comment]
Ok, it appears to be working, I made a mistake.
After launching the application and editing the settings.txt file, restarting the program would allow the changes to take effect. This is not something I was doing before.

**Comment by nereaortz** [comment]
> make sure the settings.txt file exists before doing the copy link step, so only delete the two files mentioned in the issue if they exist

I have the same error and I don't know how it was resolved in the end. Where is the settings.txt file? I don't understand how to fix it. I tried deleting the two files in Documents and nothing worked.

**Comment by HotaruBlaze** [comment]
Macos, makes it harder to see errors, you actually have #165
