### ISSUE TITLE
Unhandled exception in scriot

### ISSUE THREAD

**Issue by momobear12** [MCMi460/NSO-RPC#141]
Traceback (most recent call last):
  File "cli.py", line 88, in update
  File "api\__init__.py", line 176, in getSelf
  File "api\__init__.py", line 189, in getFriends
  File "api\__init__.py", line 354, in populateList
  File "api\__init__.py", line 351, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 833, in <module>
  File "app.py", line 352, in selfService
  File "app.py", line 487, in changeState
  File "app.py", line 484, in changeState
  File "cli.py", line 94, in update
  File "api\__init__.py", line 162, in updateLogin
  File "api\__init__.py", line 281, in __init__
KeyError: 'timestamp'

I've deleted the NSO-RPC folder in documents and redownloading but i keep getting this error and I'm not sure why

**Comment by HotaruBlaze** [comment]
API issue and duplicate issue, See #140
