### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Wumwat** [MCMi460/NSO-RPC#143]
The .exe file failed to launch and gave this error code:
Traceback (most recent call last):
  File "app.py", line 815, in <module>
  File "app.py", line 182, in writeSettings
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Username\\OneDrive\\Documents\\NSO-RPC\\settings.txt'

**Comment by HotaruBlaze** [comment]
This errors because you are using Onedrive for your documents folder, this causes alot of compatibility issues as the file is *technically* missing due to the nature of OneDrive "On-Demand".

Ill give you the easier fix to your current issue

## The Easier solution.

Put NSO-RPC.exe on another location where OneDrive would not sync by default
such as `C:\NSO-RPC\NSO-RPC.exe` and create a folder named "NSO-RPC_Data" beside the exe. 
So you'd have `C:\NSO-RPC\NSO-RPC.exe`  & `C:\NSO-RPC\NSO-RPC_Data`

This puts NSO-RPC in "Portable mode" and will use the Data folder created above instead of your documents folder.

# Note
Make sure you are using the **pre-release** version of NSO-RPC, as the latest does not contain the portable mode code and other big fixes, you can find it here: https://github.com/MCMi460/NSO-RPC/releases
