### ISSUE TITLE
crash after launching

### ISSUE THREAD

**Issue by DarthMDev** [MCMi460/NSO-RPC#155]
I even tried relinking my alt account with no dice

This is running the may 13th build

```Traceback (most recent call last):
  File "cli.pyc", line 89, in update
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 208, in getSelf
    self.getFriends()
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 221, in getFriends
    list.populateList(self)
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 397, in populateList
    raise e
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 394, in populateList
    arr = json.loads(response.text)['result']['friends']
          ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 197, in updateLogin
    self.headers['Authorization'] = 'Bearer %s' % login.account['result'].get('webApiServerCredential').get('accessToken')  # Add authorization token
                                                  ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/NSO-RPC.app/Contents/Resources/__boot__.py", line 161, in <module>
    _run()
  File "/Applications/NSO-RPC.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/NSO-RPC.app/Contents/Resources/app.py", line 851, in <module>
    window.selfService()
  File "/Applications/NSO-RPC.app/Contents/Resources/app.py", line 361, in selfService
    self.changeState()
  File "/Applications/NSO-RPC.app/Contents/Resources/app.py", line 498, in changeState
    raise e
  File "/Applications/NSO-RPC.app/Contents/Resources/app.py", line 495, in changeState
    client.update()
  File "cli.pyc", line 95, in update
  File "/Applications/NSO-RPC.app/Contents/Resources/lib/python3.11/api/__init__.py", line 199, in updateLogin
    raise Exception('Failure with authorization: %s\nLogin returns %s' % (e, login.account))
Exception: Failure with authorization: 'result'
Login returns {'status': 9403, 'errorMessage': 'Invalid token.', 'correlationId': '6be5e04b-f746e6c3'}
```

**Comment by HotaruBlaze** [comment]
Use this build for now: https://github.com/HotaruBlaze/NSO-RPC/releases/tag/v1.4.1-HB

**Comment by DarthMDev** [comment]
Thank you i guess i can close this?
