### ISSUE TITLE
This error shows when trying to boot NSO-RPC

### ISSUE THREAD

**Issue by MrBlueTopHat** [MCMi460/NSO-RPC#164]
I restarted my computer and now every time I try to open NSO-RPC, it gives this error.
NSO-RPC worked fine before restart.

Full error:

Traceback (most recent call last):
  File "app.py", line 836, in <module>
  File "app.py", line 342, in selfService
  File "app.py", line 481, in changeState
  File "app.py", line 478, in changeState
  File "cli.py", line 96, in update
  File "api\__init__.py", line 181, in updateLogin
  File "api\__init__.py", line 309, in __init__
RuntimeError: Unable to authenticate with imink. 

The F Calculation API may be experiencing issues or this build of NSO-RPC is outdated 
Please try the most upto date build of NSO-RPC before submitting an issue. 
Please check the website for more details: 
https://status.imink.app/

**Comment by MrBlueTopHat** [comment]
Edit: this is most likely an API issue but i'll just leave it here for now

**Comment by Yeetov** [comment]
got same issue
