### ISSUE TITLE
not sure whats up

### ISSUE THREAD

**Issue by pexxa** [MCMi460/NSO-RPC#167]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 836, in <module>
  File "app.py", line 342, in selfService
  File "app.py", line 481, in changeState
  File "app.py", line 478, in changeState
  File "cli.py", line 95, in update
Exception: Cannot get session token properly
![image](https://github.com/user-attachments/assets/113036f9-0876-45cf-b5f2-455f76b8b058)

**Comment by HotaruBlaze** [comment]
Duplicate of #165
