### ISSUE TITLE
NSO-RPC crashes on boot

### ISSUE THREAD

**Issue by VGmaster670** [MCMi460/NSO-RPC#30]
Error log:
```
Traceback (most recent call last):
  File "cli.py", line 77, in update
  File "api\__init__.py", line 108, in getSelf
  File "api\__init__.py", line 121, in getFriends
  File "api\__init__.py", line 288, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 561, in <module>
  File "app.py", line 151, in selfService
  File "app.py", line 258, in changeState
  File "cli.py", line 83, in update
  File "api\__init__.py", line 99, in updateLogin
KeyError: 'result'
```

**Comment by VGmaster670** [comment]
oh whoops sorry just realized this is a duplicate

**Comment by MCMi460** [comment]
I suppose updating to version 1.3.1 fixed this error?
Sorry for the inconvenience.

**Comment by VGmaster670** [comment]
yeah it did
