### ISSUE TITLE
App crashing after logging in

### ISSUE THREAD

**Issue by Sprinter05** [MCMi460/NSO-RPC#36]
Traceback (most recent call last):
  File "app.py", line 561, in <module>
  File "app.py", line 151, in selfService
  File "app.py", line 258, in changeState
  File "cli.py", line 83, in update
  File "api\__init__.py", line 110, in updateLogin
  File "api\__init__.py", line 220, in __init__
  File "api\__init__.py", line 196, in get
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MCMi460** [comment]
Yes, this appears to be the same as #35, which is an issue with imink API.

**Comment by Sprinter05** [comment]
when more less do you think it will be fixed?

**Comment by MCMi460** [comment]
I'm not sure, since it is an issue with an API I don't have control over. Once the owner of the API finds out there's an issue, it should be back on track pretty quickly. If he's not awake yet, I'd give maybe 5-6 hours?

**Comment by Sprinter05** [comment]
awesome ty

**Comment by MCMi460** [comment]
Alright, this should be fixed now. Thanks for your patience!
