### ISSUE TITLE
This happens everytime i try to open the application

### ISSUE THREAD

**Issue by coolcoleman** [MCMi460/NSO-RPC#37]
Traceback (most recent call last):
  File "cli.py", line 77, in update
  File "api\__init__.py", line 121, in getSelf
  File "api\__init__.py", line 134, in getFriends
  File "api\__init__.py", line 287, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 561, in <module>
  File "app.py", line 151, in selfService
  File "app.py", line 258, in changeState
  File "cli.py", line 83, in update
  File "api\__init__.py", line 110, in updateLogin
  File "api\__init__.py", line 221, in __init__
KeyError: 'timestamp'

**Comment by MCMi460** [comment]
Looks like imink API is down again. It'll be back up again within next few hours or so.
Sorry again for the inconvenience.

**Comment by MCMi460** [comment]
The status page can be viewed here: https://status.imink.app/
`f` token generation is the one that matters for this project.

**Comment by MCMi460** [comment]
The API is now up again.
