### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by CrazyChan4080** [MCMi460/NSO-RPC#46]
It used to work fine, but now it shows an error every time I try to open it after logging in:
```
Traceback (most recent call last):
  File "cli.py", line 81, in update
  File "api\__init__.py", line 130, in getSelf
  File "api\__init__.py", line 143, in getFriends
  File "api\__init__.py", line 297, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 564, in <module>
  File "app.py", line 158, in selfService
  File "app.py", line 265, in changeState
  File "cli.py", line 87, in update
  File "api\__init__.py", line 121, in updateLogin
KeyError: 'result'
```

Image here:
![image](https://user-images.githubusercontent.com/113630850/190474455-5c518717-591a-4f6b-a5ac-e96e872ea70f.png)

Even after deleing the "NSO-RPC" folder in the Documents directory, and even restarting my computer, I continue to get this error message right after logging into my account, when the program used to work fine before.

**Comment by CrazyChan4080** [comment]
whoops, my mistake, didn't realize someone else had already posted about this issue
