### ISSUE TITLE
unhandled exception: 'timestamp'

### ISSUE THREAD

**Issue by KlashR-Dev** [MCMi460/NSO-RPC#85]
I have an issue with running the program and this is what came up.

Traceback (most recent call last):
  File "cli.py", line 83, in update
  File "api\__init__.py", line 156, in getSelf
  File "api\__init__.py", line 169, in getFriends
  File "api\__init__.py", line 327, in populateList
  File "api\__init__.py", line 324, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 711, in <module>
  File "app.py", line 281, in selfService
  File "app.py", line 401, in changeState
  File "app.py", line 398, in changeState
  File "cli.py", line 89, in update
  File "api\__init__.py", line 142, in updateLogin
  File "api\__init__.py", line 257, in __init__
KeyError: 'timestamp'

**Comment by DarthMDev** [comment]
getting the same issue on macbook air  m1

**Comment by HotaruBlaze** [comment]
This error happens when imink is down or having issues, Looks like their was downtime earlier 

https://status.imink.app/

**Comment by MCMi460** [comment]
Now that imink is back up, I will be closing this issue. Thanks for the help, everyone!
