### ISSUE TITLE
Failed to execute script 'app' due to unhandled exception: 'timestamp'

### ISSUE THREAD

**Issue by alexsquibbs** [MCMi460/NSO-RPC#95]
**description**: so i noticed it wasnt displaying my rich presence whilst the app was running, so i closed it via the tray icon and re-opened it to be greeted by the error below. i downloaded the latest release from github to see if that would fix it, but still got the error running it both as a plain user and administrator.

**error**:
```
Traceback (most recent call last):
  File "cli.py", line 85, in update
  File "api\__init__.py", line 162, in getSelf
  File "api\__init__.py", line 175, in getFriends
  File "api\__init__.py", line 340, in populateList
  File "api\__init__.py", line 337, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 764, in <module>
  File "app.py", line 303, in selfService
  File "app.py", line 422, in changeState
  File "app.py", line 419, in changeState
  File "cli.py", line 91, in update
  File "api\__init__.py", line 148, in updateLogin
  File "api\__init__.py", line 267, in __init__
KeyError: 'timestamp'
```

**operating system**: windows 11 (version 23h2, build 25905.1000)

**Comment by MCMi460** [comment]
Hi, this is due to a 3rd party API, imink, being offline at the moment. You can check if it's online here: https://status.imink.app/

**Comment by spudpiggy** [comment]
Is this why i'm getting an invalid_token error? The app should tell you when the api is down and to expect issues

**Comment by HotaruBlaze** [comment]
timestamp is due to imink going down, invalid_token is because token generation is currently broken

**Comment by HotaruBlaze** [comment]
> Is this why i'm getting an invalid_token error? The app should tell you when the api is down and to expect issues

Temp fix build: #97

**Comment by spudpiggy** [comment]
it doesnt work?

**Comment by HotaruBlaze** [comment]
> it doesnt work?

The build I provided should be working, if its not you may have to delete your `private.txt` and start it back up.

---
Windows: `Documents\NSO-RPC`
MacOS/Linux: `~/Documents/NSO-RPC`

**Comment by HotaruBlaze** [comment]
The build got broken seemingly by a change by imink, my build no longer works.
